- aspects/macros/get_problem_id.sql
- aspects/models/problems/int_problem_hints.sql
- aspects/models/problems/int_problem_results.sql
- aspects/models/problems/learner_problem_summary.sql
- aspects/models/problems/problem_responses.sql
- aspects/models/problems/schema.yml
- aspects/tests/learner_problem_summary_uniqueness.sql
- aspects/tests/problem_results_uniqueness.sql
Models should support the following reports listed in #4 :
- problem difficulty (via `learner_problem_summary`)
- answer distributions per problem (via `problem_responses`)
- problem submission counts (also via `problem_responses`)
These models have been tested with the `force_primary_key=1` setting to ensure they make proper use of indexes.
> feat: adds models for problem interaction reports (FC-0024)

- aspects/models/enrollment/enrollments_by_day.sql
- aspects/models/enrollment/int_enrollment_windows.sql
This PR fixes a broken "acceptable values" test for `enrollments_by_day`. It also renames `stg_enrollment_windows` to `int_enrollment_windows` to be more in-line with common dbt practice.
> fix: adds enrollment_status to enrollments_by_day (FC-0024)

- aspects/models/base/sources.yml
- aspects/models/enrollment/enrollments_by_day.sql
- aspects/models/enrollment/int_enrollment_windows.sql
- aspects/models/problems/int_problem_hints.sql
- aspects/models/problems/int_problem_results.sql
- aspects/models/problems/learner_problem_summary.sql
- aspects/models/problems/problem_responses.sql
- aspects/models/problems/schema.yml
- aspects/models/video/schema.yml
- aspects/models/video/transcript_usage.sql
- aspects/models/video/video_plays.sql
Following from https://github.com/openedx/tutor-contrib-aspects/pull/193, we'll need to use `course_key` instead of `course_id` in the top-level materialized views.
> refactor: use course_key instead of course_id (FC-0024)

- aspects/tests/learner_problem_summary_uniqueness.sql
- aspects/tests/problem_results_uniqueness.sql
The tests currently fail because I forgot to update them to use `course_key` instead of `course_id` when we made that switch. My apologies for the oversight.
> fix: use course_key in tests (FC-0024)

- README.rst
Use the openedx security e-mail address instead of the Axim One.
See https://github.com/openedx/wg-security/issues/15 for details.
> Update Security E-mail Address

- aspects/models/problems/fact_learner_problem_summary.sql
- aspects/models/problems/fact_problem_responses.sql
- aspects/models/problems/int_problem_hints.sql
- aspects/models/problems/int_problem_results.sql
Fixes issues with the problem interaction models where fields weren't being passed through correctly, leading to errors at query time.
This PR also updates the strategy for joining entity names, avoiding an unnecessary join in the `fact_learner_problem_summary` model. `dbt test` now succeeds and these models correctly display data in the instructor dashboard. This should unblock the [corresponding PR in tutor-contrib-aspects](https://github.com/openedx/tutor-contrib-aspects/pull/272).
> fix: correctly pass through entity names (FC-0024)

- aspects/models/enrollment/fact_enrollments.sql
- aspects/models/problems/schema.yml
- aspects/models/video/fact_transcript_usage.sql
- aspects/models/video/fact_video_plays.sql
- aspects/models/video/schema.yml
Including `course_key` in the models used by Superset will allow us to make better use of our primary keys, thereby improving query performance and stability. The problem interaction models already had `course_key` and `problem_id` in the models so all that was needed was to bring the documentation in line with the implementation.
> feat: include course_key in final output models (FC-0033)

- README.rst
- models/base/dim_course_blocks.sql
- models/base/sources.yml
- models/problems/fact_problem_responses.sql
- models/problems/int_problem_hints.sql
- models/video/fact_transcript_usage.sql
- models/video/fact_video_plays.sql
This creates a view, `dim_course_blocks`, that leverages ClickHouse's "direct" join type to improve query performance when adding entity names to larger datasets.
This view could also be used for the `dim_course_videos` and `dim_course_problems` datasets that Superset uses for dashboard filters.
**Please note:** to get this working with Superset, I needed to grant `dictGet` permissions to the `event_sink` database for the Aspects reporting user. I can add that in a subsequent PR to use a version of this project that includes this change in the aspects tutor plugin.
> feat: create `dim_course_blocks` for entity lookup (FC-0033)

- models/base/sources.yml
- models/grading/fact_grades.sql
- models/grading/schema.yml
This introduces `fact_grades`, which joins in entity names and transforms data to be used to analyze course, subsection, and problem performance. From this model we could create charts that display high-level information about how learners are performing on courses, subsections, and problems.
> feat: add base model for grading events (FC-0033)

- .github/profiles.yml
- .github/workflows/documentation.yml
- clickhouse/config/docker_config.xml
- clickhouse/users/default-user.xml
- docker-compose.yml
This PR creates a GitHub workflow to generate the DBT docs and publish it to GitHub pages.
The destination branch is `gh-pages` and the documentation is generated on every push a main.
> feat: add dbt documentation

- macros/get_problem_id.sql
- models/problems/fact_problem_responses.sql
Responses to multi-part problems are currently excluded from `fact_problem_responses` because the regular expression for parsing problem IDs was incorrectly handling object IDs for distinct parts of problems. This PR changes the regular expression to accurately parse problem IDs while also removing duplicate problem response records (the first part in a multi-part question seems to have two records for every problem check event).
> feat: support multi-part problem responses (FC-0033)

- models/video/fact_transcript_usage.sql
- models/video/video_transcript_events.sql
This update creates a new materialized view for transcript enabled/disabled events and updates `fact_transcript_usage` to use this new MV. This should improve the performance of transcript-related charts in Superset by avoiding relying on the base `xapi_events_all_parsed` table.
> feat: add MV for transcript usage (FC-0033)

- models/base/xapi_events_all_parsed.sql
While reviewing the refactor to remove the MVs from our alembic migrations, I noticed that I missed the last update to the `xapi_events_all_parsed_mv` definition. This PR brings the dbt implementation in line with the current alembic-managed version.
> fix: use latest xapi base MV definition (FC-0033)

- macros/get_custom_schema.sql
- models/base/sources.yml
- models/base/xapi_events_all_parsed.sql
- models/completion/completion_events.sql
- models/enrollment/enrollment_events.sql
- models/forum/forum_events.sql
- models/grading/grading_events.sql
- models/problems/problem_events.sql
- models/video/video_playback_events.sql
- models/video/video_transcript_events.sql
- sample_profiles.yml
This change overrides the destination database for the materialized views that were once written to the `xapi` schema so that they can be written to the correct database again. Note: while `database` is the preferred term when it comes to dbt and ClickHouse, dbt does not seem to recognize `database` as a valid configuration parameter for model destinations, hence the use of the `schema` keyword argument in the `config` block.
This change also requires `profiles.yml` to pass `prod` as the target instead of `dev`. I have updated `sample_profiles.yml` to match the expected configuration. This also means that the [profile in tutor-contrib-aspects](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/apps/aspects/dbt/profiles.yml#L2) will need to be updated …
> fix: write MVs to xapi schema again

- models/navigation/fact_navigation.sql
- models/navigation/navigation_events.sql
- models/navigation/schema.yml
This PR adds a materialized view for navigation events and an accompanying view that enriches the MV with course and block metadata.
> feat: add models for navigation events (FC-0033)

- models/base/sources.yml
- models/base/xapi_events_all_parsed.sql
- models/completion/completion_events.sql
- models/enrollment/enrollment_events.sql
- models/forum/forum_events.sql
- models/grading/grading_events.sql
- models/navigation/navigation_events.sql
- models/problems/problem_events.sql
- models/video/video_playback_events.sql
- models/video/video_transcript_events.sql
Ralph 3.x had both a JSON "event" column and an
"event_str" text representation of the same data. 4.x drops the JSON column since it is unsupported and going to be removed from ClickHouse, and renames the text column to "event".
Ralph 4.0.0 is in beta right now, this is just for preparing to upgrade and test the changes.
> feat!: Upgrade schema to use new Ralph 4.0 event column

- models/base/xapi_events_all_parsed.sql
- models/completion/completion_events.sql
- models/enrollment/enrollment_events.sql
- models/forum/forum_events.sql
- models/grading/grading_events.sql
- models/navigation/navigation_events.sql
- models/problems/problem_events.sql
- models/video/video_playback_events.sql
- models/video/video_transcript_events.sql
This PR partitions almost all tables by year and month.
> feat: partition all tables by year and month

- requirements.txt
Fixes the issue with schemas of MVs being changed if they already exist.
> fix: Bump dbt-clickhouse to 1.7.2

- macros/get_problem_id.sql
- models/base/xapi_events_all_parsed.sql
- tests/get_problem_id.sql
- tests/get_problem_id_with_ccx.sql
This PR allows us to get the course organization for CCX courses and fixes the `get_problem_id` regex to include '@' which is part of the URL for CCX courses.
After querying: ` select * from reporting.fact_problem_responses format Vertical` it matches both course formats:
```
Row 3:
──────
emission_time:              2024-02-19 15:29:41
org:                        edunext
course_key:                 course-v1:edunext+demo+demo
course_name:                Demo
course_run:                 demo
problem_id:                 block-v1:edunext+demo+demo+type@problem+block@3c1646f7133a4c5fb4557d649e22c251
problem_name:               Checkboxes
problem_name_with_location: 2:2:0 - Checkboxes
actor_id:                   9bd74238-97cf-4bff-ab96-d98a6006cba5
responses:                  ["a correct …
```
> feat: add support for CCX courses

- macros/parse_section_codes.sql
- models/base/dim_course_blocks.sql
- models/base/schema.yml
- models/navigation/fact_navigation_completion.sql
- models/navigation/fact_navigation_dropoff.sql
- models/navigation/int_pages_per_subsection.sql
- models/navigation/schema.yml
This includes models to support engagement dropoff analyses and page view completeness, i.e. how many learners viewed all pages in a section or subsection.
`fact_navigation_dropoff` is a model with two different aggregation levels: total views are counted for each section and subsection.
`fact_navigation_completion` counts the number of pages in each section and subsection and joins that to data about page visits. Aggregations can use the `page_count` column to compare against the number of unique pages a learner has visited. If the numbers are equal, then the learner has visited every page in the section.
Here is an example query of how `fact_navigation_completeness` can answer the question "which learners viewed all pages in a subsection?":
```sql
SELECT
subsection_with_name,
actor_id, …
```
> feat: include models for pageview engagement

- .ci/config.yml
- .github/workflows/documentation.yml
- models/base/dim_user_pii.sql
- models/base/schema.yml
- models/base/sources.yml
- models/enrollment/fact_enrollment_status.sql
- models/enrollment/schema.yml
- models/forum/schema.yml
- models/grading/fact_grade_status.sql
- models/grading/fact_learner_course_grade.sql
- models/grading/fact_learner_course_status.sql
- models/grading/fact_student_status.sql
- models/grading/schema.yml
- models/navigation/schema.yml
- models/video/fact_video_plays.sql
- models/video/schema.yml
This PR creates an MV for the latest course enrollment status for a learner and renames the `fact_grade_status` to `fact_learner_status` with information of the current grade, current approving status and current enrollment status.
It also updates the `fact_video_plays` model to include video duration and visualization progress.
> feat: implement fact_student_status model

- macros/items_per_subsection.sql
- models/video/fact_video_engagement.sql
- models/video/fact_video_plays.sql
- models/video/int_videos_per_subsection.sql
- models/video/schema.yml
This adds one user-facing model (`fact_video_engagement`) and one internal model (`int_videos_per_subsection`) in order to support a chart that displays how many learners engaged with videos within a specific section or subsection. The macro `items_per_subsection` is meant to make it easier to create similar intermediate models for other item types (like problems or pages).
> feat: add models for video engagement dropoff (FC-0051)

- models/problems/fact_problem_engagement.sql
- models/problems/fact_problem_responses.sql
- models/problems/int_problems_per_subsection.sql
- models/problems/schema.yml
Similar to #61, this adds models for tracking problem engagement per section and subsection. The primary model is `fact_problem_engagement`, which relies on an intermediate model named `int_problems_per_subsection`.
> feat: add models for problem engagement (FC-0051)

- .github/workflows/coverage.yml
- models/problems/schema.yml
This should allow us to still test for coverage from forks, but avoid trying to push docs from fork PRs since they will never have the right permissions for the secrets. Testing with a fork happened here, you can see that the docs build is skipped instead of erroring: https://github.com/openedx/aspects-dbt/pull/69
> build: CI fixes, move coverage to separate workflow

- models/problems/fact_problem_responses.sql
- models/problems/fact_problem_responses_extended.sql
- models/problems/int_problem_results.sql
- models/problems/schema.yml
This change introduces a new model, `fact_problem_responses_extended`, which contains section and subsection names alongside problem results. This also includes `interaction_type`, which specifies the type of answer the problem accepts (e.g. multiple choice)
> feat: add section names to problem dataset (FC-0051)

- models/courses/dim_course_blocks_extended.sql
- models/courses/schema.yml
This change introduces another dimension table, `dim_course_blocks_extended`, which includes the section and subsection names to which each block belongs. This is included as a separate model instead of adding onto `dim_course_blocks` so as to avoid any unnecessary joins when a model requires block metadata but does not need the extra information joined into `dim_course_blocks` by this new model.
> feat: add extended course block dimension table (FC-0051)

- models/video/fact_video_plays.sql
- models/video/schema.yml
This change adds `section_with_name` and `subsection_with_name` to `fact_video_plays`. This is to be able to provide additional context to dashboard viewers about which videos are included in which sections or subsections.
> feat: include section names in fact_video_plays (FC-0051)

- models/video/fact_video_engagement.sql
- models/video/schema.yml
This change adds `course_run` to `fact_video_engagement`, which enables filtering based on course_run to any charts that rely on `fact_video_engagement`.
> fix: add course_run to video engagement dataset (FC-0051)

- .github/workflows/documentation.yml
This PR restricts the documentation workflow to only run on pushes to main.
> build: only build documentation on merge to main

- models/instance/fact_instance_actors.sql
- models/instance/fact_instance_courses.sql
- models/instance/fact_instance_enrollments.sql
- models/instance/fact_instance_events.sql
- models/instance/schema.yml
- models/users/dim_user_pii.sql
- models/users/schema.yml
- models/users/user_pii.sql
Also removes a number of user_pii fields that are currently unused and cause ClickHouse to fail to build them when run at scale.
> Add models for operator dashboard

- models/grading/fact_student_status.sql
- models/grading/schema.yml
- models/users/dim_at_risk_learners.sql
- models/users/schema.yml
This change adds the timestamp of when a learner enrolled in a course to the `fact_student_status` model. This field is then used in `dim_at_risk_learners` to support displaying a distribution of when at-risk learners enrolled in the course.
> feat: add enrollment timestamp to at-risk learners (FC-0051)

- models/users/dim_at_risk_learners.sql
- models/users/schema.yml
This change adds `grade_bucket` to the `dim_at_risk_learners` model, which can be used to display a breakdown of current course grades for at-risk learners.
> feat: add grade bucket to dim_at_risk_learners (FC-0051)

- models/video/fact_watched_video_segments.sql
- models/video/schema.yml
This PR imports the model fact_watched_video_segments from Aspects to DBT
> feat: create fact_watched_video_segments report

- .github/workflows/coverage.yml
- macros/items_per_subsection.sql
- models/problems/fact_problem_engagement.sql
- models/problems/fact_problem_engagement_per_subsection.sql
- models/problems/fact_problem_responses.sql
- models/problems/int_problem_hints.sql
- models/problems/int_problem_results.sql
- models/problems/problem_events.sql
- models/problems/responses.sql
- models/problems/schema.yml
- models/problems/section_problem_engagement.sql
- models/problems/subsection_problem_engagement.sql
- models/video/schema.yml
chore: quality fixes
chore: add missing commas
chore: remove projections
feat: move response status to a MV
feat: create responses mv
feat: refactor int problem results
chore: restore fact_problem_responses
> feat: move response status to a MV

- models/navigation/fact_navigation_completion.sql
This PR fixes an issue in which the join operation was applied twice on the user_pii dataset for the fact_navigation_completion report.
> fix: do not rejoin user PII information on fact_navigation_completion

- models/base/schema.yml
- models/base/xapi_events_all_parsed.sql
- models/completion/completion_events.sql
- models/enrollment/enrollment_events.sql
- models/forum/forum_events.sql
- models/grading/grading_events.sql
- models/instance/fact_instance_actors.sql
- models/instance/fact_instance_enrollments.sql
- models/instance/fact_instance_events.sql
- models/instance/schema.yml
- models/navigation/navigation_events.sql
- models/problems/problem_events.sql
- models/video/video_playback_events.sql
- models/video/video_transcript_events.sql
Generally for columns with less than 10k unique values this provides a noticeable performance benefit.
Accompanying PR is here: https://github.com/openedx/tutor-contrib-aspects/pull/839
> feat: Use LowCardinality for smaller columns

- .github/workflows/coverage.yml
- models/enrollment/schema.yml
- models/grading/schema.yml
- models/instance/schema.yml
- models/learners/schema.yml
- models/navigation/schema.yml
- models/problems/schema.yml
- models/video/schema.yml
- package-lock.yml
- tests/generic/test_accepted_values_xapi.sql
Fixing and updating data tests in preparation of adding unit tests
1. Added new 'acceptable_values_xapi' test to run on models that don't exist in the target schema (reporting)
2. Update 'tests' property to 'data_tests' per dbt documentation
> test: Fix data tests

- .github/profiles.yml
- models/tags/course_tags.sql
- models/tags/most_recent_course_tags.sql
- models/tags/most_recent_object_tags.sql
- models/tags/most_recent_tags.sql
- models/tags/most_recent_taxonomies.sql
- models/tags/schema.yml
- models/tags/sources.yml
This PR creates a view for having easy access to the parsed course tags. The current implementation has the following structure:
```
SELECT *
FROM reporting.course_tags
Query id: f15260ac-1c29-40e7-8a61-ee7cae127c9c
┌─course_key─────────────────────────┬─course_name──────────┬─taxonomy_name────┬─tag────────────────────┬─lineage─────────────────────────────────┐
1. │ course-v1:OpenedX+DemoX+DemoCourse │ Open edX Demo Course │ Example Taxonomy │ Electronic instruments │ ['Electronic instruments']              │
2. │ course-v1:OpenedX+DemoX+DemoCourse │ Open edX Demo Course │ Example Taxonomy │ Percussion instruments │ ['Percussion instruments']              │
3. │ course-v1:OpenedX+DemoX+DemoCourse │ Open edX Demo Course │ Example Taxonomy │ Bowed strings          │ ['String instruments', …
```
> feat: create dataset for tagging

- models/video/section_video_engagement.sql
- models/video/subsection_video_engagement.sql
- models/video/unit_tests.yaml
The left-most table the section and subsection video engagement MVs were a view, which doesn't properly trigger inserts causing the MVs to be outdated.
> fix: use table instead of view for video engagement mv

- models/users/user_pii.sql
If no external ID records have been created we can still the `user_profile` information.
> fix: invert join side to user user_profiles as base table

- models/_docs/docs.md
- models/base/schema.yml
- models/base/sources.yml
- models/courses/schema.yml
- models/courses/sources.yml
- models/enrollment/schema.yml
- models/grading/schema.yml
- models/instance/schema.yml
- models/navigation/schema.yml
- models/problems/schema.yml
- models/tags/schema.yml
- models/tags/sources.yml
- models/users/schema.yml
- models/users/sources.yml
- models/video/schema.yml
1. Add data types and descriptions to source files
2. Pull out descriptions for frequently used columns into separate file. This prevents the same columns having different descriptions.
> docs: Fill in missing doc descriptions and types
